### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by RnbWd** [azer/bud#8]
I've been using bud with gulp for the last 6 months, and I find that it's actually much more pleasant to work with than gulp's default task manager (orchestrator). I recently forked bud and made some changes that may be of interest to the community. It can be found [here](https://github.com/RnbWd/bud), and I'm working on documentation [here](https://github.com/RnbWd/gulp-bud). Everything is hosted on github and privately [here](https://nasync.com) - I don't want to pollute the global npm namespace *quite yet*. Here are the changes: 

**task** refers to `require('bud')` and **t** refers to `task('name', function(t)`

**Breaking:**

- ~~task.files and t.files are depreciated~~
- task.files is a function that returns the files 
- ~~file globs are no longer separated into individual files internally~~
- ~~chokidar has been replaced with [gulp-sane-watch](https://github.com/ggkovacs/gulp-sane-watch)~~

CHOKIDAR IS STILL USED :)

**Additions:**

- task has two additional methods: path and dest, which both accept files, but those files are not watched
- t has quite a few additional methods: path, glob, src, dest, and end
- t.glob & t.path hold a reference to files passed via task.watch and task.path, respectively
- t.src and t.dest map on one-to-one with gulp.src and gulp.dest, respectively
- t.end is a wrapper for [end-of-stream](https://www.npmjs.com/package/end-of-stream), calling t.done when the stream ends

**Rationale and Patterns**

Previously, I had been using this pattern to combine gulp streams and bud:

```
var task = require('task')
var vfs = require('vinyl-fs')
var eos = require('end-of-stream')

task('scripts', function(t) {
  var stream = vfs.src('./src/**')
   .pipe(..)
   .pipe(vfs.dest('./public'));
   
  eos(stream, t.done);
})
```

This pattern isn't that bad, and completely manageable on it's own, but there's a lot of repetition. I actually separate all my tasks into different files that I'll require into one index.js, so my main task file looks something like this:

```
var task = require('bud')
var scripts = require('./scripts')

task('scripts', scripts);
task('default', task.once('scripts');
```

I also found that it was nice to include files like this:

```
task('scripts', function(t) {
  var stream = vfs.src(t.files)
   .pipe(..)
   ...
})
```

But things got messy very quickly when I was watching files, and folders needed to be built before others, etc. So, I created a way to pass files that aren't necessarily watched:

```
task('scripts', task.path('./src/**'), function(t) {
  var stream = vfs.src(t.path)
   .pipe(..)
   ...
})
```

I also included vfs into t, and created a pattern where I can define the files in my index.js without having to rename every name in individual modules:

```
task('scripts', task.path('./src/**').dest('./public'), function(t) {
  var stream = t.src() // t.src(t.path)
   .pipe(..)
   .pipe(t.dest()) // t.dest(t.options._dest)
})
```

The final piece was wrapping end-of-stream, to get a pattern looking like this:

```
task('scripts', task.path('./src/**').dest('./public'), scripts);

function scripts(t) {
  t.end(
    t.src() 
     .pipe(..)
     .pipe(t.dest())
  );
}
```

Last but not least, I replaced with chokidar with  [gulp-sane-watch](https://github.com/ggkovacs/gulp-sane-watch), which is basically a globbing file-watch wrapper on top of [sane](https://www.npmjs.com/package/sane). Updating chokidar broke the library, I tried like 3 other watching libraries, which all failed, except for this one, which seems to be the best solution. 

I am interested in actively developing this and contributing to bud core if there is desire to merge any of the features. Including vinyl-fs seems like a pretty big leap, but gulp has such a great ecosystem backing it up that it seemed appropriate :)

**Comment by azer** [comment]
Hi @RnbWd , 

I'm back to working on bud but my english is not so good for reading long comments. could you list the changes that you'd like to see ?

**Comment by RnbWd** [comment]
nm

**Comment by RnbWd** [comment]
I rewrote most of the library but the API syntax is very similar. I noticed some redundant code recently and I can go back through what you have changed to be more specific

**Comment by RnbWd** [comment]
btw I found some bugs and unused code during the process :) I haven't seen the changes you've made here in the last year but I know the library very well and would love to contribute

**Comment by RnbWd** [comment]
To clarify - here is my rewrite : https://github.com/RnbWd/chronic

1) Smaller codebase - with a much larger API toolkit - many npm packages used

   - [meow](https://github.com/sindresorhus/meow) - for cli passing in syntax into tasks similarly
   - [npm-exec-spawn](https://github.com/mafintosh/npm-execspawn) - 1 to 1 mapping with exec
   - lots of stream helpers with [vinyl-fs](https://github.com/wearefractal/vinyl-fs), making the library a potential replacement for **gulp** 
    
2) Biggest philosophical change was with the role of `t` in `function(t) { t.(x)}`

 - `t` has double as many methods, including the methods used by `gulp` (`t.src()` `t.dest()` `t.build()` `t.pump()` `t.eos()`) - which are just thin wrappers on top of `vinyl.src`, `pump`, `end-of-stream`
- in reference to `gulp` specifically, the main utility was being able to pass into `t` file system data and modularize the tasks

3) I added a method which is set 'true' while a task is running and 'false' when the task finishes, which I used internally to task was really finished.

Honestly the fork has become so divergent from the original library that it's like `bud` is the skeleton, and everything else is different now.

**Comment by RnbWd** [comment]
I would love to submit pull requests for aspects of the libraries that work identical - I've very interested in the new features implemented recently. If you're curious, I would recommend looking at the [chronic](https://github.com/RnbWd/chronic) to see what's different in about handling tasks, control flow, exec, etc. - that library is currently in 'full rewrite' into es6, only just begun

**Comment by azer** [comment]
I see, interesting... yeah I'm recently putting some efforts on speeding up my development... thx for sharing your work, it looks pretty good

**Comment by RnbWd** [comment]
Thank you - this library is incredible! From my original [Rationale](https://github.com/RnbWd/chronic/wiki/Old-Rational):

> After discovering azer's bud, I began using it as my primary task manger. At this point, you can stop reading and just use vinyl-fs with bud because that is ultimately what this library is all about...

Here's the original [API](https://github.com/RnbWd/chronic/wiki/Old-API), and ['todo list`](https://github.com/RnbWd/chronic/wiki/Old-Todo), which have been moved into the wiki. Two interesting ideas from the todo-list that might be interesting (although I haven't worked on them yet):

 - integrate some philosophy and modules from [folktale](http://docs.folktalejs.org/en/latest/index.html#) - specifically [data.task](https://github.com/folktale/data.task)

> The Task(a, b) structure represents values that depend on time. This allows one to model time-based effects explicitly, such that one can have full knowledge of when they're dealing with delayed computations, latency, or anything that can not be computed immediately.

- [maxogen/atomic-queue](https://github.com/maxogden/atomic-queue) to persist the state / order of tasks if it crashes

> a crash friendly queue that persists queue state and can restart. uses a worker pool and has configurable concurrency
 
I'm glad you started working on it again!

**Comment by RnbWd** [comment]
I apologize if there is a language barrier - luckily the code should speak for itself if I submit a pull request or something like that
